# Generated by Django 4.0.3 on 2022-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=25)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=50)),
                ('barch_code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
