# Generated by Django 4.0.3 on 2022-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=250)),
                ('from_add', models.CharField(max_length=250)),
                ('delivery_date', models.DateField()),
                ('item_id', models.CharField(max_length=250)),
                ('item_name', models.CharField(max_length=250)),
                ('model_no', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
