# Generated by Django 4.0.3 on 2022-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
