# Generated by Django 4.0.3 on 2022-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('item_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
