# Generated by Django 4.0.3 on 2022-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='balance_sheet_id',
            field=models.CharField(max_length=10),
        ),
    ]
