# Generated by Django 4.0.3 on 2022-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('address', models.CharField(max_length=450)),
                ('item_name', models.CharField(max_length=250)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
